INSERT INTO troops (name, tier, type, banner, occupation, faction, culture, image) VALUES
  ('Vlandian Voulgier', 5, 'Infantry', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Voulgier.PNG'),
  ('Vlandian Vanguard', 5, 'Cavalry', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Vanguard.PNG'),
  ('Vlandian Swordsman', 4, 'Infantry', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Swordsman.PNG'),
  ('Vlandian Squire', 2, 'Cavalry', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Squire.PNG'),
  ('Vlandian Spearman', 3, 'Infantry', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Spearman.PNG'),
  ('Vlandian Sharpshooter', 5, 'Archer', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Sharpshooter.PNG'),
  ('Vlandian Sergeant', 5, 'Infantry', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Sergeant.PNG'),
  ('Vlandian Recruit', 1, 'Infantry', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Recruit.PNG'),
  ('Vlandian Pikeman', 5, 'Infantry', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Pikeman.PNG'),
  ('Vlandian Light Cavalry', 3, 'Cavalry', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Light_Cavalry.PNG'),
  ('Vlandian Levy Crossbowman', 2, 'Archer', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Levy_Crossbowman.PNG'),
  ('Vlandian Knight', 4, 'Cavalry', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Knight.PNG'),
  ('Vlandian Hardened Crossbowman', 4, 'Archer', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Hardened_Crossbowman.PNG'),
  ('Vlandian Galland', 3, 'Cavalry', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Galland.PNG'),
  ('Vlandian Footman', 2, 'Infantry', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Footman.PNG'),
  ('Vlandian Crossbowman', 3, 'Archer', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Crossbowman.PNG'),
  ('Vlandian Champion', 5, 'Cavalry', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Champion.PNG'),
  ('Vlandian Cavalry', 4, 'Cavalry', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Cavalry.PNG'),
  ('Vlandian Billman', 4, 'Infantry', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Billman.PNG'),
  ('Vlandian Banner Knight', 6, 'Cavalry', 'Factions/Kingdom_of_Vlandia.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Vlandia/Vlandian_Banner_Knight.PNG'),
  ('Sturgian Archer', 4, 'Archer', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Sturgian_Archer.PNG'),
  ('Sturgian Brigand', 3, 'Infantry', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Sturgian_Brigand.PNG'),
  ('Sturgian Druzhinnik', 5, 'Cavalry', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Sturgian_Druzhinnik.PNG'),
  ('Sturgian Druzhinnik Champion', 6, 'Cavalry', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Sturgian_Druzhinnik_Champion.PNG'),
  ('Sturgian Hardened Brigand', 4, 'Cavalry', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Sturgian_Hardened_Brigand.PNG'),
  ('Sturgian Heavy Axeman', 5, 'Infantry', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Sturgian_Heavy_Axeman.PNG'),
  ('Sturgian Heavy Spearman', 5, 'Infantry', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Sturgian_Heavy_Spearman.PNG'),
  ('Sturgian Horse Raider', 5, 'Cavalry', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Sturgian_Horse_Raider.PNG'),
  ('Sturgian Hunter', 3, 'Archer', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Sturgian_Hunter.PNG'),
  ('Sturgian Line Breaker', 4, 'Infantry', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Sturgian_Line_Breaker.PNG'),
  ('Sturgian Otrok', 2, 'Infantry', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Sturgian_Otrok.PNG'),
  ('Sturgian Recruit', 1, 'Infantry', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Sturgian_Recruit.PNG'),
  ('Sturgian Soldier', 3, 'Infantry', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Sturgian_Soldier.PNG'),
  ('Sturgian Spearman', 4, 'Infantry', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Sturgian_Spearman.PNG'),
  ('Sturgian Veteran Bowman', 5, 'Archer', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Sturgian_Veteran_Bowman.PNG'),
  ('Sturgian Warrior', 6, 'Infantry', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Sturgian_Warrior.PNG'),
  ('Sturgian Woodsman', 2, 'Infantry', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Sturgian_Woodsman.PNG'),
  ('Varyag', 3, 'Infantry', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Varyag.PNG'),
  ('Varyag Veteran', 4, 'Infantry', 'Factions/Principality_of_Sturgia.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Sturgia/Varyag_Veteran.PNG'),
  ('Khuzait Archer', 4, 'Archer', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Archer.PNG'),
  ('Khuzait Darkhan', 5, 'Infantry', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Darkhan.PNG'),
  ('Khuzait Footman', 2, 'Infantry', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Footman.PNG'),
  ('Khuzait Heavy Horse Archer', 5, 'Mounted Archer', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Heavy_Horse_Archer.PNG'),
  ('Khuzait Heavy Lancer', 5, 'Cavalry', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Heavy_Lancer.PNG'),
  ('Khuzait Horse Archer', 4, 'Mounted Archer', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Horse_Archer.PNG'),
  ('Khuzait Horseman', 3, 'Cavalry', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Horseman.PNG'),
  ('Khuzait Hunter', 3, 'Archer', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Hunter.PNG'),
  ('Khuzait Khan''s Guard', 6, 'Mounted Archer', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Khan''s_Guard.PNG'),
  ('Khuzait Kheshig', 5, 'Mounted Archer', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Kheshig.PNG'),
  ('Khuzait Lancer', 4, 'Cavalry', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Lancer.PNG'),
  ('Khuzait Marksman', 5, 'Archer', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Marksman.PNG'),
  ('Khuzait Noble''s Son', 2, 'Mounted Archer', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Noble''s_Son.PNG'),
  ('Khuzait Nomad', 1, 'Infantry', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Nomad.PNG'),
  ('Khuzait Qanqli', 3, 'Mounted Archer', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Qanqli.PNG'),
  ('Khuzait Raider', 3, 'Mounted Archer', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Raider.PNG'),
  ('Khuzait Spear Infantry', 4, 'Infantry', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Spear_Infantry.PNG'),
  ('Khuzait Spearman', 3, 'Infantry', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Spearman.PNG'),
  ('Khuzait Torguud', 4, 'Mounted Archer', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Torguud.PNG'),
  ('Khuzait Tribal Warrior', 2, 'Infantry', 'Factions/Khuzait_Khanate.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Khuzait/Khuzait_Tribal_Warrior.PNG'),
  ('Imperial Archer', 2, 'Archer', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Archer.PNG'),
  ('Imperial Bucellarii', 5, 'Mounted Archer', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Bucellarii.PNG'),
  ('Imperial Cataphract', 5, 'Cavalry', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Cataphract.PNG'),
  ('Imperial Crossbowman', 4, 'Archer', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Crossbowman.PNG'),
  ('Imperial Elite Cataphract', 6, 'Cavalry', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Elite_Cataphract.PNG'),
  ('Imperial Elite Menavliaton', 5, 'Infantry', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Elite_Menavliaton.PNG'),
  ('Imperial Equite', 3, 'Cavalry', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Equite.PNG'),
  ('Imperial Heavy Horseman', 4, 'Cavalry', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Heavy_Horseman.PNG'),
  ('Imperial Infantryman', 2, 'Infantry', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Infantryman.PNG'),
  ('Imperial Legionary', 5, 'Infantry', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Legionary.PNG'),
  ('Imperial Menavliaton', 4, 'Infantry', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Menavliaton.PNG'),
  ('Imperial Palatine Guard', 5, 'Archer', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Palatine_Guard.PNG'),
  ('Imperial Recruit', 1, 'Infantry', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Recruit.PNG'),
  ('Imperial Sergeant Crossbowman', 5, 'Archer', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Sergeant_Crossbowman.PNG'),
  ('Imperial Trained Archer', 3, 'Archer', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Trained_Archer.PNG'),
  ('Imperial Trained Infantryman', 3, 'Infantry', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Trained_Infantryman.PNG'),
  ('Imperial Veteran Archer', 4, 'Archer', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Veteran_Archer.PNG'),
  ('Imperial Veteran Infantryman', 4, 'Infantry', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Veteran_Infantryman.PNG'),
  ('Imperial Vigla Recruit', 2, 'Infantry', 'Factions/Calradic_Empire.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Empire/Imperial_Vigla_Recruit.PNG'),
  ('Battanian Horseman', 5, 'Cavalry', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Horseman.PNG'),
  ('Battanian Clan Warrior', 2, 'Infantry', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Clan_Warrior.PNG'),
  ('Battanian Falxman', 4, 'Infantry', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Falxman.PNG'),
  ('Battanian Oathsworn', 5, 'Infantry', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Oathsworn.PNG'),
  ('Battanian Picked Warrior', 4, 'Infantry', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Picked_Warrior.PNG'),
  ('Battanian Raider', 3, 'Infantry', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Raider.PNG'),
  ('Battanian Scout', 4, 'Cavalry', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Scout.PNG'),
  ('Battanian Skirmisher', 3, 'Infantry', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Skirmisher.PNG'),
  ('Battanian Trained Warrior', 3, 'Infantry', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Trained_Warrior.PNG'),
  ('Battanian Veteran Skirmisher', 4, 'Infantry', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Veteran_Skirmisher.PNG'),
  ('Battanian Volunteer', 1, 'Infantry', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Volunteer.PNG'),
  ('Battanian Wood Runner', 2, 'Infantry', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Wood_Runner.PNG'),
  ('Battanian Veteran Falxman', 5, 'Infantry', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Veteran_Falxman.PNG'),
  ('Battanian Wildling', 5, 'Infantry', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Wildling.PNG'),
  ('Battanian Mounted Skirmisher', 5, 'Cavalry', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Mounted_Skirmisher.PNG'),
  ('Battanian Highborn Youth', 2, 'Archer', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Highborn_Youth.PNG'),
  ('Battanian Highborn Warrior', 3, 'Archer', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Highborn_Warrior.PNG'),
  ('Battanian Hero', 4, 'Archer', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Hero.PNG'),
  ('Battanian Fian', 5, 'Archer', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Fian.PNG'),
  ('Battanian Fian Champion', 6, 'Archer', 'Factions/High_Kingdom_of_the_Battanians.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Battania/Battanian_Fian_Champion.PNG'),
  ('Aserai Archer', 4, 'Archer', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Archer.PNG'),
  ('Aserai Faris', 4, 'Cavalry', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Faris.PNG'),
  ('Aserai Footman', 3, 'Infantry', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Footman.PNG'),
  ('Aserai Infantry', 4, 'Infantry', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Infantry.PNG'),
  ('Aserai Light Archer', 3, 'Archer', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Light_Archer.PNG'),
  ('Aserai Mamluke Axeman', 3, 'Infantry', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Mamluke_Axeman.PNG'),
  ('Aserai Mamluke Cavalry', 4, 'Mounted Archer', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Mamluke_Cavalry.PNG'),
  ('Aserai Mamluke Guard', 4, 'Infantry', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Mamluke_Guard.PNG'),
  ('Aserai Mamluke Heavy Cavalry', 5, 'Mounted Archer', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Mamluke_Heavy_Cavalry.PNG'),
  ('Aserai Mamluke Palace Guard', 5, 'Infantry', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Mamluke_Palace_Guard.PNG'),
  ('Aserai Mamluke Regular', 3, 'Cavalry', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Mamluke_Regular.PNG'),
  ('Aserai Mamluke Soldier', 2, 'Infantry', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Mamluke_Soldier.PNG'),
  ('Aserai Master Archer', 5, 'Archer', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Master_Archer.PNG'),
  ('Aserai Recruit', 1, 'Infantry', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Recruit.PNG'),
  ('Aserai Tribal Horseman', 3, 'Cavalry', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Tribal_Horseman.PNG'),
  ('Aserai Tribesman', 2, 'Infantry', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Tribesman.PNG'),
  ('Aserai Vanguard Faris', 6, 'Cavalry', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Vanguard_Faris.PNG'),
  ('Aserai Veteran Faris', 5, 'Cavalry', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Veteran_Faris.PNG'),
  ('Aserai Veteran Infantry', 5, 'Infantry', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Veteran_Infantry.PNG'),
  ('Aserai Youth', 2, 'Cavalry', 'Factions/Aserai_Sultanate.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Aserai/Aserai_Youth.PNG'),
  ('Marauder', 3, 'Mounted Archer', 'Factions/None.png', 'Bandit', 'None', 'Steppe Bandits', 'Units/Steppe Bandits/Marauder.PNG'),
  ('Raider', 4, 'Mounted Archer', 'Factions/None.png', 'Bandit', 'None', 'Steppe Bandits', 'Units/Steppe Bandits/Raider.PNG'),
  ('Steppe Bandit', 2, 'Cavalry', 'Factions/None.png', 'Bandit', 'None', 'Steppe Bandits', 'Units/Steppe Bandits/Steppe_Bandit.PNG'),
  ('Steppe Bandit Boss', 5, 'Mounted Archer', 'Factions/None.png', 'Bandit', 'None', 'Steppe Bandits', 'Units/Steppe Bandits/Steppe_Bandit_Boss.PNG'),
  ('Sea Raider', 2, 'Infantry', 'Factions/None.png', 'Bandit', 'None', 'Sea Raiders', 'Units/Sea Raider/Sea_Raider.PNG'),
  ('Sea Raider Boss', 5, 'Infantry', 'Factions/None.png', 'Bandit', 'None', 'Sea Raiders', 'Units/Sea Raider/Sea_Raider_Boss.PNG'),
  ('Sea Raider Chief', 4, 'Infantry', 'Factions/None.png', 'Bandit', 'None', 'Sea Raiders', 'Units/Sea Raider/Sea_Raider_Chief.PNG'),
  ('Sea Raider Warrior', 3, 'Infantry', 'Factions/None.png', 'Bandit', 'None', 'Sea Raiders', 'Units/Sea Raider/Sea_Raider_Warrior.PNG'),
  ('Brigand', 3, 'Infantry', 'Factions/None.png', 'Bandit', 'None', 'Mountain Bandits', 'Units/Mountain Bandits/Brigand.PNG'),
  ('Highwayman', 4, 'Cavalry', 'Factions/None.png', 'Bandit', 'None', 'Mountain Bandits', 'Units/Mountain Bandits/Highwayman.PNG'),
  ('Hillman', 2, 'Infantry', 'Factions/None.png', 'Bandit', 'None', 'Mountain Bandits', 'Units/Mountain Bandits/Hillman.PNG'),
  ('Mountain Bandit Boss', 5, 'Infantry', 'Factions/None.png', 'Bandit', 'None', 'Mountain Bandits', 'Units/Mountain Bandits/Mountain_Bandit_Boss.PNG'),
  ('Bushwacker', 2, 'Archer', 'Factions/None.png', 'Bandit', 'None', 'Forest Bandits', 'Units/Forest Bandits/Bushwacker.PNG'),
  ('Forest Bandit', 4, 'Archer', 'Factions/None.png', 'Bandit', 'None', 'Forest Bandits', 'Units/Forest Bandits/Forest_Bandit.PNG'),
  ('Forest Bandit Boss', 5, 'Archer', 'Factions/None.png', 'Bandit', 'None', 'Forest Bandits', 'Units/Forest Bandits/Forest_Bandit_Boss.PNG'),
  ('Freebooter', 3, 'Archer', 'Factions/None.png', 'Bandit', 'None', 'Forest Bandits', 'Units/Forest Bandits/Freebooter.PNG'),
  ('Bedouin Rover', 2, 'Infantry', 'Desert Bandits', 'Bandit', '', '', 'Units/Desert Bandits/Bedouin_Rover.PNG'),
  ('Desert Bandit Boss', 5, 'Cavalry', 'Factions/None.png', 'Bandit', 'None', 'Desert Bandits', 'Units/Desert Bandits/Desert_Bandit_Boss.PNG'),
  ('Harami', 4, 'Cavalry', 'Factions/None.png', 'Bandit', 'None', 'Desert Bandits', 'Units/Desert Bandits/Harami.PNG'),
  ('Nomad Bandit', 3, 'Cavalry', 'Factions/None.png', 'Bandit', 'None', 'Desert Bandits', 'Units/Desert Bandits/Nomad_Bandit.PNG'),
  ('Hired Spear', 3, 'Infantry', 'Factions/None.png', 'Mercenary', 'None', 'None', 'Units/Hired Men/Hired_Spear.PNG'),
  ('Hired Pike', 4, 'Infantry', 'Factions/None.png', 'Mercenary', 'None', 'None', 'Units/Hired Men/Hired_Pike.PNG'),
  ('Hired Elite Pike', 5, 'Infantry', 'Factions/None.png', 'Mercenary', 'None', 'None', 'Units/Hired Men/Hired_Elite_Pike.PNG'),
  ('Hired Crossbow', 4, 'Archer', 'Factions/None.png', 'Mercenary', 'None', 'None', 'Units/Hired Men/Hired_Crossbow.PNG'),
  ('Elite Hired Crossbow', 5, 'Archer', 'Factions/None.png', 'Mercenary', 'None', 'None', 'Units/Hired Men/Elite_Hired_Crossbow.PNG'),
  ('Elite Mercenary Maceman', 5, 'Infantry', 'Factions/None.png', 'Mercenary', 'None', 'None', 'Units/Sellswords/Elite_Mercenary_Maceman.PNG'),
  ('Mercenary Maceman', 4, 'Infantry', 'Factions/None.png', 'Mercenary', 'None', 'None', 'Units/Sellswords/Mercenary_Maceman.PNG'),
  ('Outrider', 4, 'Mounted Archer', 'Factions/None.png', 'Mercenary', 'None', 'None', 'Units/Sellswords/Outrider.PNG'),
  ('Sellsword', 3, 'Infantry', 'Factions/None.png', 'Mercenary', 'None', 'None', 'Units/Sellswords/Sellsword.PNG'),
  ('Veteran Outrider', 5, 'Mounted Archer', 'Factions/None.png', 'Mercenary', 'None', 'None', 'Units/Sellswords/Veteran_Outrider.PNG'),
  ('Gallant Sword Sister', 5, 'Mounted Archer', 'Factions/Calradic_Empire.png', 'Mercenary', 'Calradic Empire', 'Empire', 'Units/Sword Sister/Gallant_Sword_Siter.PNG'),
  ('Sisterhood Follower', 3, 'Archer', 'Factions/Calradic_Empire.png', 'Mercenary', 'Calradic Empire', 'Empire', 'Units/Sword Sister/Sisterhood_Follower.PNG'),
  ('Sword Sister', 4, 'Archer', 'Factions/Calradic_Empire.png', 'Mercenary', 'Calradic Empire', 'Empire', 'Units/Sword Sister/Sword_Sister.PNG'),
  ('Veteran Sword Sister', 5, 'Archer', 'Factions/Calradic_Empire.png', 'Mercenary', 'Calradic Empire', 'Empire', 'Units/Sword Sister/Veteran_Sword_Sister.PNG'),
  ('Beni Zilal Recruit', 2, 'Cavalry', 'Factions/Beni_Zilal.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Beni Zilal/Beni_Zilal_Recruit.png'),
  ('Beni Zilal Soldier', 3, 'Cavalry', 'Factions/Beni_Zilal.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Beni Zilal/Beni_Zilal_Soldier.png'),
  ('Beni Zilal Royal Guard', 4, 'Cavalry', 'Factions/Beni_Zilal.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Beni Zilal/Beni_Zilal_Royal_Guard.png'),
  ('Jawwal Recruit', 2, 'Infantry', 'Factions/Jawwal.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Jawwal/Jawwal_Recruit.png'),
  ('Jawwal Camel Rider', 3, 'Infantry', 'Factions/Jawwal.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Jawwal/Jawwal_Camel_Rider.png'),
  ('Jawwal Bedouin', 4, 'Cavalry', 'Factions/Jawwal.png', 'Soldier', 'Aserai Sultanate', 'Aserai', 'Units/Jawwal/Jawwal_Bedouin.png'),
  ('Koleman', 2, 'Cavalry', 'Factions/Ghilman.png', 'Soldier', 'Aserai Sultanate', 'Darshi', 'Units/Darshi/Koleman.PNG'),
  ('Ghilman', 3, 'Cavalry', 'Factions/Ghilman.png', 'Soldier', 'Aserai Sultanate', 'Darshi', 'Units/Darshi/Ghilman.PNG'),
  ('Ghulam', 4, 'Cavalry', 'Factions/Ghilman.png', 'Soldier', 'Aserai Sultanate', 'Darshi', 'Units/Darshi/Ghulam.PNG'),
  ('Young Wolf', 2, 'Archer', 'Factions/Wolfskins.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Wolfskins/Young_Wolf.png'),
  ('Seasoned Wolf', 3, 'Archer', 'Factions/Wolfskins.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Wolfskins/Seasoned_Wolf.png'),
  ('Chosen Wolf', 4, 'Archer', 'Factions/Wolfskins.png', 'Soldier', 'High Kingdom of the Battanians', 'Battania', 'Units/Wolfskins/Chosen_Wolf.png'),
  ('Karakhergit Nomad', 2, 'Mounted Archer', 'Factions/Karakhergit.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Karakhergit/Karakhergit_Nomad.png'),
  ('Karakhergit Rider', 3, 'Mounted Archer', 'Factions/Karakhergit.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Karakhergit/Karakhergit_Rider.png'),
  ('Karakhergit Elder', 4, 'Mounted Archer', 'Factions/Karakhergit.png', 'Soldier', 'Khuzait Khanate', 'Khuzait', 'Units/Karakhergit/Karakhergit_Elder.png'),
  ('Recruit Forester', 2, 'Archer', 'Factions/Forest_People.png', 'Soldier', 'Principality of Sturgia', 'Vakken', 'Units/Vakken/Recruit_Forester.PNG'),
  ('Expert Forester', 3, 'Archer', 'Factions/Forest_People.png', 'Soldier', 'Principality of Sturgia', 'Vakken', 'Units/Vakken/Expert_Forester.PNG'),
  ('Veteran Forester', 4, 'Archer', 'Factions/Forest_People.png', 'Soldier', 'Principality of Sturgia', 'Vakken', 'Units/Vakken/Veteran_Forester.PNG'),
  ('Lake Rat Recruit', 2, 'Infantry', 'Factions/Lake_Rats.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Lake Rats/Lake_Rat_Recruit.png'),
  ('Lake Rat Veteran', 3, 'Infantry', 'Factions/Lake_Rats.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Lake Rats/Lake_Rat_Veteran.png'),
  ('Lake Rat Wrecker', 4, 'Infantry', 'Factions/Lake_Rats.png', 'Soldier', 'Principality of Sturgia', 'Sturgia', 'Units/Lake Rats/Lake_Rat_Wrecker.png'),
  ('Skolder Recruit', 2, 'Infantry', 'Factions/Skolderbroda.png', 'Soldier', 'Principality of Sturgia', 'Nord', 'Units/Skolderbroda/Skolder_Recruit.png'),
  ('Skolder Warrior Broda', 3, 'Infantry', 'Factions/Skolderbroda.png', 'Soldier', 'Principality of Sturgia', 'Nord', 'Units/Skolderbroda/Skolder_Warrior_Broda.png'),
  ('Skolder Veteran Broda', 4, 'Infantry', 'Factions/Skolderbroda.png', 'Soldier', 'Principality of Sturgia', 'Nord', 'Units/Skolderbroda/Skolder_Veteran_Broda.png'),
  ('Sprout', 2, 'Archer', 'Factions/Brotherhood_of_the_Woods.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Brotherhood of the Woods/Sprout.png'),
  ('Sapling', 3, 'Archer', 'Factions/Brotherhood_of_the_Woods.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Brotherhood of the Woods/Sapling.png'),
  ('Arboreal', 4, 'Archer', 'Factions/Brotherhood_of_the_Woods.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Brotherhood of the Woods/Arboreal.png'),
  ('Boar Novice', 2, 'Archer', 'Factions/Company_of_the_Golden_Boar.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Company of the Golden Boar/Boar_Novice.png'),
  ('Boar Veteran', 3, 'Archer', 'Factions/Company_of_the_Golden_Boar.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Company of the Golden Boar/Boar_Veteran.png'),
  ('Boar Champion', 4, 'Archer', 'Factions/Company_of_the_Golden_Boar.png', 'Soldier', 'Kingdom of Vlandia', 'Vlandia', 'Units/Company of the Golden Boar/Boar_Champion.png'),
  ('Recruit Eleftheroi', 2, 'Cavalry', 'Factions/Eleftheroi.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Eleftheroi/Recruit_Eleftheroi.png'),
  ('Expert Eleftheroi', 3, 'Cavalry', 'Factions/Eleftheroi.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Eleftheroi/Expert_Eleftheroi.png'),
  ('Veteran Eleftheroi', 4, 'Cavalry', 'Factions/Eleftheroi.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Eleftheroi/Veteran_Eleftheroi.png'),
  ('Spark', 2, 'Infantry', 'Factions/Embers_of_the_Flame.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Embers of the Flame/Spark.png'),
  ('Flame', 3, 'Infantry', 'Factions/Embers_of_the_Flame.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Embers of the Flame/Flame.png'),
  ('Blaze', 4, 'Infantry', 'Factions/Embers_of_the_Flame.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Embers of the Flame/Blaze.png'),
  ('Hidden Pawn', 2, 'Infantry', 'Factions/Hidden_Hand.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Hidden Hand/Hidden_Pawn.png'),
  ('Hidden Hand', 3, 'Infantry', 'Factions/Hidden_Hand.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Hidden Hand/Hidden_Hand.png'),
  ('Puppeteer', 4, 'Infantry', 'Factions/Hidden_Hand.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Hidden Hand/Puppeteer.png'),
  ('Hastati', 2, 'Infantry', 'Factions/Legion_of_the_Betrayed.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Legion of the Betrayed/Hastati.png'),
  ('Principes', 3, 'Infantry', 'Factions/Legion_of_the_Betrayed.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Legion of the Betrayed/Principes.png'),
  ('Triarii', 4, 'Infantry', 'Factions/Legion_of_the_Betrayed.png', 'Soldier', 'Calradic Empire', 'Empire', 'Units/Legion of the Betrayed/Triarii.png');