INSERT INTO map_areas (name, faction, type, coordinates) VALUES
  ('Ain Baliq Castle', 'Aserai', 'Castle', '[385,800]'::jsonb),
  ('Barihal Castle', 'Aserai', 'Castle', '[405,851]'::jsonb),
  ('Jamayeh Castle', 'Aserai', 'Castle', '[440,857]'::jsonb),
  ('Medeni Castle', 'Aserai', 'Castle', '[269,558]'::jsonb),
  ('Sahel Castle', 'Aserai', 'Castle', '[578,327]'::jsonb),
  ('Shibal Zumr Castle', 'Aserai', 'Castle', '[185,317]'::jsonb),
  ('Tamnuh Castle', 'Aserai', 'Castle', '[344,418]'::jsonb),
  ('Tubilis Castle', 'Aserai', 'Castle', '[548,460]'::jsonb),
  ('Uqba Castle', 'Aserai', 'Castle', '[165,109]'::jsonb),
  ('Ab Comer Castle', 'Battania', 'Castle', '[507,787]'::jsonb),
  ('Aster Castle', 'Battania', 'Castle', '[482,393]'::jsonb),
  ('Druimmor Castle', 'Battania', 'Castle', '[793,760]'::jsonb),
  ('Flintolg Castle', 'Battania', 'Castle', '[701,577]'::jsonb),
  ('Llanoc Hen Castle', 'Battania', 'Castle', '[767,594]'::jsonb),
  ('Pendraic Castle', 'Battania', 'Castle', '[412,827]'::jsonb),
  ('Rhemtoil Castle', 'Battania', 'Castle', '[859,350]'::jsonb),
  ('Uthelaim Castle', 'Battania', 'Castle', '[815,284]'::jsonb),
  ('Akiser Castle', 'Khuzait', 'Castle', '[339,427]'::jsonb),
  ('Dinar Castle', 'Khuzait', 'Castle', '[760,325]'::jsonb),
  ('Erzenur Castle', 'Khuzait', 'Castle', '[776,507]'::jsonb),
  ('Hakkun Castle', 'Khuzait', 'Castle', '[648,790]'::jsonb),
  ('Kaysar Castle', 'Khuzait', 'Castle', '[544,721]'::jsonb),
  ('Khimli Castle', 'Khuzait', 'Castle', '[677,294]'::jsonb),
  ('Simira Castle', 'Khuzait', 'Castle', '[816,352]'::jsonb),
  ('Tepes Castle', 'Khuzait', 'Castle', '[830,791]'::jsonb),
  ('Usek Castle', 'Khuzait', 'Castle', '[567,199]'::jsonb),
  ('Mazhadan Castle', 'Sturgia', 'Castle', '[821,537]'::jsonb),
  ('Kranirog Castle', 'Sturgia', 'Castle', '[253,669]'::jsonb),
  ('Nevyansk Castle', 'Sturgia', 'Castle', '[711,827]'::jsonb),
  ('Ov Castle', 'Sturgia', 'Castle', '[590,866]'::jsonb),
  ('Takor Castle', 'Sturgia', 'Castle', '[447,114]'::jsonb),
  ('Urikskala Castle', 'Sturgia', 'Castle', '[192,611]'::jsonb),
  ('Ustokol Castle', 'Sturgia', 'Castle', '[474,511]'::jsonb),
  ('Vladiv Castle', 'Sturgia', 'Castle', '[156,823]'::jsonb),
  ('Caleus Castle', 'Vlandia', 'Castle', '[854,724]'::jsonb),
  ('Drapand Castle', 'Vlandia', 'Castle', '[141,737]'::jsonb),
  ('Hongard Castle', 'Vlandia', 'Castle', '[464,735]'::jsonb),
  ('Ormanfard Castle', 'Vlandia', 'Castle', '[603,766]'::jsonb),
  ('Talivel Castle', 'Vlandia', 'Castle', '[244,358]'::jsonb),
  ('Tirby Castle', 'Vlandia', 'Castle', '[171,755]'::jsonb),
  ('Usanc Castle', 'Vlandia', 'Castle', '[851,348]'::jsonb),
  ('Verecsand Castle', 'Vlandia', 'Castle', '[308,760]'::jsonb),
  ('Ataconia Castle', 'Northern Empire', 'Castle', '[631,822]'::jsonb),
  ('Atriom Castle', 'Northern Empire', 'Castle', '[140,705]'::jsonb),
  ('Gaos Castle', 'Northern Empire', 'Castle', '[292,562]'::jsonb),
  ('Epinosa Castle', 'Northern Empire', 'Castle', '[268,485]'::jsonb),
  ('Lochana Castle', 'Northern Empire', 'Castle', '[626,472]'::jsonb),
  ('Mecalovea Castle', 'Northern Empire', 'Castle', '[597,358]'::jsonb),
  ('Rhesos Castle', 'Northern Empire', 'Castle', '[439,848]'::jsonb),
  ('Syratos Castle', 'Northern Empire', 'Castle', '[397,366]'::jsonb),
  ('Varagos Castle', 'Northern Empire', 'Castle', '[594,470]'::jsonb),
  ('Chanopsis Castle', 'Southern Empire', 'Castle', '[474,380]'::jsonb),
  ('Corenia Castle', 'Southern Empire', 'Castle', '[203,591]'::jsonb),
  ('Jogurys Castle', 'Southern Empire', 'Castle', '[213,667]'::jsonb),
  ('Lavenia Castle', 'Southern Empire', 'Castle', '[526,696]'::jsonb),
  ('Melion Castle', 'Southern Empire', 'Castle', '[515,112]'::jsonb),
  ('Morenia Castle', 'Southern Empire', 'Castle', '[537,605]'::jsonb),
  ('Odrysa Castle', 'Southern Empire', 'Castle', '[353,303]'::jsonb),
  ('Sestadaim Castle', 'Southern Empire', 'Castle', '[633,898]'::jsonb),
  ('Garontor Castle', 'Western Empire', 'Castle', '[470,573]'::jsonb),
  ('Gersegos Castle', 'Western Empire', 'Castle', '[565,414]'::jsonb),
  ('Hertogea Castle', 'Western Empire', 'Castle', '[622,235]'::jsonb),
  ('Onica Castle', 'Western Empire', 'Castle', '[320,251]'::jsonb),
  ('Oristocorys Castle', 'Western Empire', 'Castle', '[842,824]'::jsonb),
  ('Thorios Castle', 'Western Empire', 'Castle', '[637,682]'::jsonb),
  ('Thractorae Castle', 'Western Empire', 'Castle', '[825,264]'::jsonb),
  ('Veron Castle', 'Western Empire', 'Castle', '[620,566]'::jsonb),
  ('Askar', 'Aserai', 'Town', '[592,829]'::jsonb),
  ('Hubyar', 'Aserai', 'Town', '[493,102]'::jsonb),
  ('Husn Fulq', 'Aserai', 'Town', '[470,445]'::jsonb),
  ('Iyakis', 'Aserai', 'Town', '[453,258]'::jsonb),
  ('Qasira', 'Aserai', 'Town', '[537,722]'::jsonb),
  ('Quyaz', 'Aserai', 'Town', '[425,242]'::jsonb),
  ('Razih', 'Aserai', 'Town', '[733,452]'::jsonb),
  ('Sanala', 'Aserai', 'Town', '[487,336]'::jsonb),
  ('Car Banseth', 'Battania', 'Town', '[282,635]'::jsonb),
  ('Dunglanys', 'Battania', 'Town', '[369,499]'::jsonb),
  ('Marunath', 'Battania', 'Town', '[483,228]'::jsonb),
  ('Pen Cannoc', 'Battania', 'Town', '[705,873]'::jsonb),
  ('Seonon', 'Battania', 'Town', '[711,502]'::jsonb),
  ('Akkalat', 'Khuzait', 'Town', '[217,354]'::jsonb),
  ('Baltakhand', 'Khuzait', 'Town', '[603,191]'::jsonb),
  ('Chaikand', 'Khuzait', 'Town', '[753,579]'::jsonb),
  ('Makeb', 'Khuzait', 'Town', '[406,137]'::jsonb),
  ('Odokh', 'Khuzait', 'Town', '[707,819]'::jsonb),
  ('Ortongard', 'Khuzait', 'Town', '[395,404]'::jsonb),
  ('Balgard', 'Sturgia', 'Town', '[837,189]'::jsonb),
  ('Omor', 'Sturgia', 'Town', '[554,714]'::jsonb),
  ('Revyl', 'Sturgia', 'Town', '[862,379]'::jsonb),
  ('Sibir', 'Sturgia', 'Town', '[472,461]'::jsonb),
  ('Tyal', 'Sturgia', 'Town', '[258,404]'::jsonb),
  ('Varcheg', 'Sturgia', 'Town', '[614,253]'::jsonb),
  ('Varnovapol', 'Sturgia', 'Town', '[651,483]'::jsonb),
  ('Charas', 'Vlandia', 'Town', '[257,670]'::jsonb),
  ('Galend', 'Vlandia', 'Town', '[350,807]'::jsonb),
  ('Jaculan', 'Vlandia', 'Town', '[310,302]'::jsonb),
  ('Ocs Hall', 'Vlandia', 'Town', '[413,455]'::jsonb),
  ('Ostican', 'Vlandia', 'Town', '[693,730]'::jsonb),
  ('Pravend', 'Vlandia', 'Town', '[573,462]'::jsonb),
  ('Rovalt', 'Vlandia', 'Town', '[229,484]'::jsonb),
  ('Sargot', 'Vlandia', 'Town', '[743,776]'::jsonb),
  ('Amprela', 'Northern Empire', 'Town', '[520,496]'::jsonb),
  ('Argoron', 'Northern Empire', 'Town', '[563,362]'::jsonb),
  ('Diathma', 'Northern Empire', 'Town', '[130,120]'::jsonb),
  ('Epicrotea', 'Northern Empire', 'Town', '[555,525]'::jsonb),
  ('Myzea', 'Northern Empire', 'Town', '[618,767]'::jsonb),
  ('Saneopa', 'Northern Empire', 'Town', '[427,636]'::jsonb),
  ('Danustica', 'Southern Empire', 'Town', '[468,544]'::jsonb),
  ('Lycaron', 'Southern Empire', 'Town', '[381,604]'::jsonb),
  ('Onira', 'Southern Empire', 'Town', '[189,386]'::jsonb),
  ('Phycaon', 'Southern Empire', 'Town', '[891,405]'::jsonb),
  ('Poros', 'Southern Empire', 'Town', '[138,302]'::jsonb),
  ('Syronea', 'Southern Empire', 'Town', '[619,714]'::jsonb),
  ('Vostrum', 'Southern Empire', 'Town', '[356,432]'::jsonb),
  ('Amitatys', 'Western Empire', 'Town', '[564,813]'::jsonb),
  ('Jalmarys', 'Western Empire', 'Town', '[200,479]'::jsonb),
  ('Lageta', 'Western Empire', 'Town', '[716,427]'::jsonb),
  ('Ortysia', 'Western Empire', 'Town', '[558,118]'::jsonb),
  ('Rhotae', 'Western Empire', 'Town', '[797,783]'::jsonb),
  ('Zeonica', 'Western Empire', 'Town', '[720,662]'::jsonb),
  ('Abba', 'Aserai', 'Village', '[514,795]'::jsonb),
  ('Abghan', 'Aserai', 'Village', '[690,161]'::jsonb),
  ('Abu Khih', 'Aserai', 'Village', '[752,516]'::jsonb),
  ('Ain Baliq', 'Aserai', 'Village', '[295,188]'::jsonb),
  ('Asmait', 'Aserai', 'Village', '[347,338]'::jsonb),
  ('Barihal', 'Aserai', 'Village', '[354,710]'::jsonb),
  ('Baq', 'Aserai', 'Village', '[579,848]'::jsonb),
  ('Bir Seif', 'Aserai', 'Village', '[201,723]'::jsonb),
  ('Bunqaz', 'Aserai', 'Village', '[885,795]'::jsonb),
  ('Ezbet Nahul', 'Aserai', 'Village', '[757,428]'::jsonb),
  ('Fanab', 'Aserai', 'Village', '[322,823]'::jsonb),
  ('Hamoshawat', 'Aserai', 'Village', '[767,490]'::jsonb),
  ('Hiblet', 'Aserai', 'Village', '[226,293]'::jsonb),
  ('Hoqqa', 'Aserai', 'Village', '[324,724]'::jsonb),
  ('Jahasim', 'Aserai', 'Village', '[789,163]'::jsonb),
  ('Kuqa', 'Aserai', 'Village', '[427,737]'::jsonb),
  ('Lamesa', 'Aserai', 'Village', '[400,185]'::jsonb),
  ('Mabwaz', 'Aserai', 'Village', '[457,308]'::jsonb),
  ('Medeni', 'Aserai', 'Village', '[418,242]'::jsonb),
  ('Mijayit', 'Aserai', 'Village', '[578,445]'::jsonb),
  ('Mussum', 'Aserai', 'Village', '[367,312]'::jsonb),
  ('Nahlan', 'Aserai', 'Village', '[266,129]'::jsonb),
  ('Qablab', 'Aserai', 'Village', '[710,301]'::jsonb),
  ('Qidnar', 'Aserai', 'Village', '[669,250]'::jsonb),
  ('Sahel', 'Aserai', 'Village', '[374,756]'::jsonb),
  ('Shibal Zumr', 'Aserai', 'Village', '[452,586]'::jsonb),
  ('Tamnuh', 'Aserai', 'Village', '[577,783]'::jsonb),
  ('Tasheba', 'Aserai', 'Village', '[417,214]'::jsonb),
  ('Tubilis', 'Aserai', 'Village', '[726,710]'::jsonb),
  ('Uqba', 'Aserai', 'Village', '[881,589]'::jsonb),
  ('Wadar', 'Aserai', 'Village', '[836,537]'::jsonb),
  ('Zalm', 'Aserai', 'Village', '[266,496]'::jsonb),
  ('Ab Comer', 'Battania', 'Village', '[132,467]'::jsonb),
  ('Andurn', 'Battania', 'Village', '[223,700]'::jsonb),
  ('Aster', 'Battania', 'Village', '[260,867]'::jsonb),
  ('Ath Cafal', 'Battania', 'Village', '[668,611]'::jsonb),
  ('Beglomuar', 'Battania', 'Village', '[459,278]'::jsonb),
  ('Bog Beth', 'Battania', 'Village', '[437,704]'::jsonb),
  ('Bryn Glas', 'Battania', 'Village', '[211,530]'::jsonb),
  ('Cantrec', 'Battania', 'Village', '[669,608]'::jsonb),
  ('Claig Ban', 'Battania', 'Village', '[432,855]'::jsonb),
  ('Dalmengus', 'Battania', 'Village', '[345,886]'::jsonb),
  ('Diantogmail', 'Battania', 'Village', '[395,455]'::jsonb),
  ('Druimmor', 'Battania', 'Village', '[350,274]'::jsonb),
  ('Durn', 'Battania', 'Village', '[720,875]'::jsonb),
  ('Ebereth', 'Battania', 'Village', '[669,777]'::jsonb),
  ('Fenon Etir', 'Battania', 'Village', '[775,715]'::jsonb),
  ('Flintolg', 'Battania', 'Village', '[340,828]'::jsonb),
  ('Gainseth', 'Battania', 'Village', '[797,817]'::jsonb),
  ('Geunat Nal', 'Battania', 'Village', '[104,644]'::jsonb),
  ('Glenlithrig', 'Battania', 'Village', '[549,711]'::jsonb),
  ('Glintor', 'Battania', 'Village', '[899,364]'::jsonb),
  ('Imlagh', 'Battania', 'Village', '[285,138]'::jsonb),
  ('Inveth', 'Battania', 'Village', '[354,615]'::jsonb),
  ('Lindorn', 'Battania', 'Village', '[773,626]'::jsonb),
  ('Llanoc Hen', 'Battania', 'Village', '[788,529]'::jsonb),
  ('Mag Arba', 'Battania', 'Village', '[755,172]'::jsonb),
  ('Morihig', 'Battania', 'Village', '[601,281]'::jsonb),
  ('Pendraic', 'Battania', 'Village', '[628,435]'::jsonb),
  ('Rhemtoil', 'Battania', 'Village', '[750,769]'::jsonb),
  ('Seordas', 'Battania', 'Village', '[597,401]'::jsonb),
  ('Swenryn', 'Battania', 'Village', '[107,539]'::jsonb),
  ('Tor Leiad', 'Battania', 'Village', '[815,109]'::jsonb),
  ('Tor Melina', 'Battania', 'Village', '[874,494]'::jsonb),
  ('Uthelaim', 'Battania', 'Village', '[352,550]'::jsonb),
  ('Akiser', 'Khuzait', 'Village', '[312,409]'::jsonb),
  ('Asalig', 'Khuzait', 'Village', '[137,838]'::jsonb),
  ('Danara', 'Khuzait', 'Village', '[838,830]'::jsonb),
  ('Dinar', 'Khuzait', 'Village', '[411,416]'::jsonb),
  ('Erzenur', 'Khuzait', 'Village', '[212,552]'::jsonb),
  ('Esme', 'Khuzait', 'Village', '[719,691]'::jsonb),
  ('Fisnar', 'Khuzait', 'Village', '[781,803]'::jsonb),
  ('Gereden', 'Khuzait', 'Village', '[522,155]'::jsonb),
  ('Hakkun', 'Khuzait', 'Village', '[332,396]'::jsonb),
  ('Hanekhy', 'Khuzait', 'Village', '[813,773]'::jsonb),
  ('Ispantar', 'Khuzait', 'Village', '[782,483]'::jsonb),
  ('Kamshar', 'Khuzait', 'Village', '[768,346]'::jsonb),
  ('Karahalli', 'Khuzait', 'Village', '[491,265]'::jsonb),
  ('Karahan', 'Khuzait', 'Village', '[484,606]'::jsonb),
  ('Karakalat', 'Khuzait', 'Village', '[693,421]'::jsonb),
  ('Kaysar', 'Khuzait', 'Village', '[116,109]'::jsonb),
  ('Khimli', 'Khuzait', 'Village', '[659,856]'::jsonb),
  ('Kiraz', 'Khuzait', 'Village', '[663,341]'::jsonb),
  ('Kohi Ajik', 'Khuzait', 'Village', '[543,463]'::jsonb),
  ('Kuruluk', 'Khuzait', 'Village', '[673,317]'::jsonb),
  ('Mazen', 'Khuzait', 'Village', '[406,557]'::jsonb),
  ('Mivanjan', 'Khuzait', 'Village', '[388,125]'::jsonb),
  ('Nutyuk', 'Khuzait', 'Village', '[571,686]'::jsonb),
  ('Okhutan', 'Khuzait', 'Village', '[653,585]'::jsonb),
  ('Omrotok', 'Khuzait', 'Village', '[792,606]'::jsonb),
  ('Pabastan', 'Khuzait', 'Village', '[266,611]'::jsonb),
  ('Payam', 'Khuzait', 'Village', '[312,183]'::jsonb),
  ('Ransam', 'Khuzait', 'Village', '[441,416]'::jsonb),
  ('Shapeshte', 'Khuzait', 'Village', '[682,315]'::jsonb),
  ('Simira', 'Khuzait', 'Village', '[759,546]'::jsonb),
  ('Tepes', 'Khuzait', 'Village', '[378,852]'::jsonb),
  ('Tismil', 'Khuzait', 'Village', '[211,217]'::jsonb),
  ('Ulaan', 'Khuzait', 'Village', '[841,148]'::jsonb),
  ('Urunjan', 'Khuzait', 'Village', '[506,656]'::jsonb),
  ('Usek', 'Khuzait', 'Village', '[764,788]'::jsonb),
  ('Alebat', 'Sturgia', 'Village', '[302,439]'::jsonb),
  ('Alov', 'Sturgia', 'Village', '[767,570]'::jsonb),
  ('Borchovagorka', 'Sturgia', 'Village', '[875,583]'::jsonb),
  ('Bukits', 'Sturgia', 'Village', '[867,218]'::jsonb),
  ('Chornobas', 'Sturgia', 'Village', '[440,458]'::jsonb),
  ('Dnin', 'Sturgia', 'Village', '[742,765]'::jsonb),
  ('Dvorusta', 'Sturgia', 'Village', '[180,128]'::jsonb),
  ('Ferkh', 'Sturgia', 'Village', '[182,246]'::jsonb),
  ('Forin', 'Sturgia', 'Village', '[253,442]'::jsonb),
  ('Glavstrom', 'Sturgia', 'Village', '[270,442]'::jsonb),
  ('Ismilkorg', 'Sturgia', 'Village', '[282,175]'::jsonb),
  ('Karbur', 'Sturgia', 'Village', '[268,366]'::jsonb),
  ('Kargrev', 'Sturgia', 'Village', '[230,768]'::jsonb),
  ('Korsyas', 'Sturgia', 'Village', '[334,468]'::jsonb),
  ('Kranirog', 'Sturgia', 'Village', '[111,496]'::jsonb),
  ('Kvol', 'Sturgia', 'Village', '[611,351]'::jsonb),
  ('Mazhadan', 'Sturgia', 'Village', '[775,733]'::jsonb),
  ('Nevyansk', 'Sturgia', 'Village', '[513,180]'::jsonb),
  ('Omkany', 'Sturgia', 'Village', '[718,628]'::jsonb),
  ('Ov', 'Sturgia', 'Village', '[158,589]'::jsonb),
  ('Radakmed', 'Sturgia', 'Village', '[578,613]'::jsonb),
  ('Rodobas', 'Sturgia', 'Village', '[769,573]'::jsonb),
  ('Safna', 'Sturgia', 'Village', '[282,284]'::jsonb),
  ('Skorin', 'Sturgia', 'Village', '[518,546]'::jsonb),
  ('Takor', 'Sturgia', 'Village', '[356,188]'::jsonb),
  ('Urikskala', 'Sturgia', 'Village', '[469,663]'::jsonb),
  ('Ustokol', 'Sturgia', 'Village', '[372,164]'::jsonb),
  ('Visibrot', 'Sturgia', 'Village', '[143,562]'::jsonb),
  ('Vladiv', 'Sturgia', 'Village', '[231,278]'::jsonb),
  ('Yangutum', 'Sturgia', 'Village', '[407,828]'::jsonb),
  ('Zhemyan', 'Sturgia', 'Village', '[265,482]'::jsonb),
  ('Alantas', 'Vlandia', 'Village', '[783,537]'::jsonb),
  ('Alorstan', 'Vlandia', 'Village', '[738,452]'::jsonb),
  ('Arromanc', 'Vlandia', 'Village', '[118,370]'::jsonb),
  ('Caleus', 'Vlandia', 'Village', '[124,775]'::jsonb),
  ('Calioc', 'Vlandia', 'Village', '[898,213]'::jsonb),
  ('Cananc', 'Vlandia', 'Village', '[631,656]'::jsonb),
  ('Chornad', 'Vlandia', 'Village', '[210,702]'::jsonb),
  ('Drapand', 'Vlandia', 'Village', '[749,583]'::jsonb),
  ('Deriat', 'Vlandia', 'Village', '[366,276]'::jsonb),
  ('Etirburg', 'Vlandia', 'Village', '[616,500]'::jsonb),
  ('Ferton', 'Vlandia', 'Village', '[694,788]'::jsonb),
  ('Fregian', 'Vlandia', 'Village', '[245,845]'::jsonb),
  ('Furbec', 'Vlandia', 'Village', '[491,384]'::jsonb),
  ('Halisvust', 'Vlandia', 'Village', '[578,350]'::jsonb),
  ('Hongard', 'Vlandia', 'Village', '[232,714]'::jsonb),
  ('Horsger', 'Vlandia', 'Village', '[546,293]'::jsonb),
  ('Larnac', 'Vlandia', 'Village', '[625,855]'::jsonb),
  ('Mareiven', 'Vlandia', 'Village', '[337,778]'::jsonb),
  ('Marin', 'Vlandia', 'Village', '[106,175]'::jsonb),
  ('Mot', 'Vlandia', 'Village', '[428,589]'::jsonb),
  ('Ormanfard', 'Vlandia', 'Village', '[506,465]'::jsonb),
  ('Oritan', 'Vlandia', 'Village', '[301,219]'::jsonb),
  ('Palisont', 'Vlandia', 'Village', '[865,843]'::jsonb),
  ('Rodetan', 'Vlandia', 'Village', '[157,141]'::jsonb),
  ('Rulund', 'Vlandia', 'Village', '[675,396]'::jsonb),
  ('Savinth', 'Vlandia', 'Village', '[852,250]'::jsonb),
  ('Sirindac', 'Vlandia', 'Village', '[781,501]'::jsonb),
  ('Talivel', 'Vlandia', 'Village', '[351,340]'::jsonb),
  ('Tirby', 'Vlandia', 'Village', '[249,434]'::jsonb),
  ('Usanc', 'Vlandia', 'Village', '[630,257]'::jsonb),
  ('Valanby', 'Vlandia', 'Village', '[437,654]'::jsonb),
  ('Verecsand', 'Vlandia', 'Village', '[391,444]'::jsonb),
  ('Vesin', 'Vlandia', 'Village', '[499,360]'::jsonb),
  ('Aeoria', 'Northern Empire', 'Village', '[183,864]'::jsonb),
  ('Agalmon', 'Northern Empire', 'Village', '[303,882]'::jsonb),
  ('Alatys', 'Northern Empire', 'Village', '[440,258]'::jsonb),
  ('Alosea', 'Northern Empire', 'Village', '[677,815]'::jsonb),
  ('Ataconia', 'Northern Empire', 'Village', '[787,886]'::jsonb),
  ('Atrion', 'Northern Empire', 'Village', '[224,623]'::jsonb),
  ('Avasinton', 'Northern Empire', 'Village', '[346,198]'::jsonb),
  ('Boreagora', 'Northern Empire', 'Village', '[775,365]'::jsonb),
  ('Crios', 'Northern Empire', 'Village', '[331,250]'::jsonb),
  ('Dyopalis', 'Northern Empire', 'Village', '[379,565]'::jsonb),
  ('Epinosa', 'Northern Empire', 'Village', '[657,239]'::jsonb),
  ('Enoisa', 'Northern Empire', 'Village', '[509,364]'::jsonb),
  ('Gaos', 'Northern Empire', 'Village', '[807,178]'::jsonb),
  ('Gymos', 'Northern Empire', 'Village', '[899,727]'::jsonb),
  ('Hetania', 'Northern Empire', 'Village', '[301,896]'::jsonb),
  ('Jeracos', 'Northern Empire', 'Village', '[151,214]'::jsonb),
  ('Lochana', 'Northern Empire', 'Village', '[180,316]'::jsonb),
  ('Marathea', 'Northern Empire', 'Village', '[733,629]'::jsonb),
  ('Masangara', 'Northern Empire', 'Village', '[297,396]'::jsonb),
  ('Mecalovea', 'Northern Empire', 'Village', '[599,753]'::jsonb),
  ('Nortanisa', 'Northern Empire', 'Village', '[739,629]'::jsonb),
  ('Orthra', 'Northern Empire', 'Village', '[502,468]'::jsonb),
  ('Pons', 'Northern Empire', 'Village', '[857,292]'::jsonb),
  ('Potamis', 'Northern Empire', 'Village', '[117,419]'::jsonb),
  ('Rhesos', 'Northern Empire', 'Village', '[231,637]'::jsonb),
  ('Samatha', 'Northern Empire', 'Village', '[212,564]'::jsonb),
  ('Stathymos', 'Northern Empire', 'Village', '[263,688]'::jsonb),
  ('Syratos', 'Northern Empire', 'Village', '[151,743]'::jsonb),
  ('Tememos', 'Northern Empire', 'Village', '[664,813]'::jsonb),
  ('Themys', 'Northern Empire', 'Village', '[255,285]'::jsonb),
  ('Varagos', 'Northern Empire', 'Village', '[347,222]'::jsonb),
  ('Vealos', 'Northern Empire', 'Village', '[858,814]'::jsonb),
  ('Alision', 'Southern Empire', 'Village', '[243,378]'::jsonb),
  ('Amycon', 'Southern Empire', 'Village', '[161,748]'::jsonb),
  ('Atphynia', 'Southern Empire', 'Village', '[565,540]'::jsonb),
  ('Avalyps', 'Southern Empire', 'Village', '[126,507]'::jsonb),
  ('Caira', 'Southern Empire', 'Village', '[635,884]'::jsonb),
  ('Canoros', 'Southern Empire', 'Village', '[165,612]'::jsonb),
  ('Canterion', 'Southern Empire', 'Village', '[794,135]'::jsonb),
  ('Chanopsis', 'Southern Empire', 'Village', '[352,427]'::jsonb),
  ('Corenia', 'Southern Empire', 'Village', '[379,204]'::jsonb),
  ('Erebulos', 'Southern Empire', 'Village', '[516,285]'::jsonb),
  ('Ethemisa', 'Southern Empire', 'Village', '[671,656]'::jsonb),
  ('Eunalica', 'Southern Empire', 'Village', '[238,582]'::jsonb),
  ('Gorcorys', 'Southern Empire', 'Village', '[812,332]'::jsonb),
  ('Jogurys', 'Southern Empire', 'Village', '[502,250]'::jsonb),
  ('Lanthas', 'Southern Empire', 'Village', '[615,584]'::jsonb),
  ('Lartusys', 'Southern Empire', 'Village', '[160,167]'::jsonb),
  ('Melion', 'Southern Empire', 'Village', '[864,736]'::jsonb),
  ('Metachia', 'Southern Empire', 'Village', '[695,729]'::jsonb),
  ('Morenia', 'Southern Empire', 'Village', '[187,139]'::jsonb),
  ('Odrysa', 'Southern Empire', 'Village', '[638,866]'::jsonb),
  ('Parasemnos', 'Southern Empire', 'Village', '[219,385]'::jsonb),
  ('Polisia', 'Southern Empire', 'Village', '[784,705]'::jsonb),
  ('Popsia', 'Southern Empire', 'Village', '[714,242]'::jsonb),
  ('Psotai', 'Southern Empire', 'Village', '[139,656]'::jsonb),
  ('Sagolina', 'Southern Empire', 'Village', '[102,831]'::jsonb),
  ('Sagora', 'Southern Empire', 'Village', '[490,699]'::jsonb),
  ('Saldannis', 'Southern Empire', 'Village', '[585,276]'::jsonb),
  ('Sestadaim', 'Southern Empire', 'Village', '[770,327]'::jsonb),
  ('Spotia', 'Southern Empire', 'Village', '[288,826]'::jsonb),
  ('Tegresos', 'Southern Empire', 'Village', '[428,355]'::jsonb),
  ('Tevea', 'Southern Empire', 'Village', '[185,859]'::jsonb),
  ('Vargonis', 'Southern Empire', 'Village', '[722,643]'::jsonb),
  ('Zestea', 'Southern Empire', 'Village', '[279,423]'::jsonb),
  ('Aegosca', 'Western Empire', 'Village', '[188,101]'::jsonb),
  ('Alsasos', 'Western Empire', 'Village', '[680,102]'::jsonb),
  ('Arpotis', 'Western Empire', 'Village', '[575,638]'::jsonb),
  ('Bergum', 'Western Empire', 'Village', '[124,249]'::jsonb),
  ('Carphenion', 'Western Empire', 'Village', '[789,515]'::jsonb),
  ('Dradios', 'Western Empire', 'Village', '[511,765]'::jsonb),
  ('Elipa', 'Western Empire', 'Village', '[279,730]'::jsonb),
  ('Elvania', 'Western Empire', 'Village', '[158,633]'::jsonb),
  ('Gamardan', 'Western Empire', 'Village', '[650,600]'::jsonb),
  ('Garontor', 'Western Empire', 'Village', '[483,213]'::jsonb),
  ('Gersegos', 'Western Empire', 'Village', '[878,625]'::jsonb),
  ('Goleryn', 'Western Empire', 'Village', '[627,846]'::jsonb),
  ('Garengolia', 'Western Empire', 'Village', '[600,337]'::jsonb),
  ('Hertogea', 'Western Empire', 'Village', '[560,116]'::jsonb),
  ('Leblenion', 'Western Empire', 'Village', '[716,503]'::jsonb),
  ('Lysia', 'Western Empire', 'Village', '[506,303]'::jsonb),
  ('Montos', 'Western Empire', 'Village', '[736,331]'::jsonb),
  ('Neocorys', 'Western Empire', 'Village', '[149,725]'::jsonb),
  ('Nideon', 'Western Empire', 'Village', '[174,390]'::jsonb),
  ('Onica', 'Western Empire', 'Village', '[509,269]'::jsonb),
  ('Oristocorys', 'Western Empire', 'Village', '[257,341]'::jsonb),
  ('Phasos', 'Western Empire', 'Village', '[589,459]'::jsonb),
  ('Primessos', 'Western Empire', 'Village', '[622,743]'::jsonb),
  ('Tarcutis', 'Western Empire', 'Village', '[859,391]'::jsonb),
  ('Thersenion', 'Western Empire', 'Village', '[569,546]'::jsonb),
  ('Thorios', 'Western Empire', 'Village', '[392,560]'::jsonb),
  ('Thractorae', 'Western Empire', 'Village', '[451,755]'::jsonb),
  ('Vathea', 'Western Empire', 'Village', '[282,139]'::jsonb),
  ('Veron', 'Western Empire', 'Village', '[161,234]'::jsonb),
  ('Vinela', 'Western Empire', 'Village', '[495,887]'::jsonb),
  ('Zeocorys', 'Western Empire', 'Village', '[650,755]'::jsonb);